-- INSERT INTO categories (recipe_id, user_id, comment) 
-- VALUES (1 , 1, "Wow! Your recipe is fantastic!"),
--   (2 , 2, "I can't get enough of this recipe!"),
--   (3 , 3, "Not my favourite meal but still good."),
--   (4 , 4, "Next time I will add more salt."),
--   (5 , 5, "Never making this recipe again!"),
--   (1 , 1, "Share more recipes! This was amazing!"),
--   (2 , 2, "The instructions could be more clear."),
--   (3 , 3, "10/10 would make this recipe again."),
--   (4 , 4, "I think I missed an ingredient."),
--   (5 , 5, "Going to make this for my girlfriend next time.");
